<?php

/**
 * Implements hook_library_info().
 */
function tocify_library_info() {
  $libraries['tocify'] = array(
    'title' => 'Tocify',
    'website' => 'http://gregfranko.com/jquery.tocify.js/',
    'version' => '1.9.0',
    'js' => array(
      drupal_get_path('module', 'tocify') . '/jquery.tocify.js' => array(),
      drupal_get_path('module', 'tocify') . '/tocify.js' => array(),
    ),
    'css' => array(
      drupal_get_path('module', 'tocify') . '/jquery.tocify.css' => array(),
    ),
    'dependencies' => array(
      array('system', 'jquery'),
      array('system', 'jquery.ui.widget'),
    ),
  );
  return $libraries;
}
